version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/dist
hooks:
  BeforeInstall:
    - location: beforeinstall.sh
      timeout: 60
    - location: install.sh
      timeout: 240
  ApplicationStart:
    - location: start.sh
      timeout: 60
  ValidateService:
    - location: validate.sh
      timeout: 30